version: '3.6'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=10d'
    ports:
      - 9090:9090

services:
  prometheus_yaml:
    image: promyaml:1
    container_name: prometheus_yaml
    restart: unless-stopped
    volumes:
      - ./prometheus:/data/prometheus
    ports:
      - 9091:8000



volumes:
  prometheus_data: 
