version: "3"
services:
    grafana:
     image: grafana/grafana
     container_name: grafana
     ports:
       - "3000:3000"
     restart: always

     volumes:
      - /data/grafana/var/lib/grafana:/var/lib/grafana
      - /data/grafana/etc/grafana:/etc/grafana

