#metricbeat.config.modules:
#  path: ${path.config}/modules.d/*.yml
#  reload.enabled: false


metricbeat.modules:
- module: prometheus
  metricsets: ["remote_write"]
  host: "0.0.0.0"
  port: "9201"

  #processors:
  #  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash-promethues:5044"]

