version: '3.6'

services:
  prometheus:
    image: prom/snmp-exporter:latest
    container_name: prometheus-snmp
    restart: unless-stopped
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    command: --config.file=/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116

